### ISSUE TITLE
Update Dependencies and Test Functionality

### ISSUE THREAD

**Issue by fabiodmota** [eclipse-tractusx/vas-country-risk#20]
Product Name: [vas-country-risk-frontend](https://github.com/eclipse-tractusx/vas-country-risk-frontend)

### Description
This issue is about updating the dependencies in the `package.json` file. All fixed dependencies should be removed, unless they are necessary to correct vulnerabilities. 

After the dependencies have been updated, the Jest unit tests should be run to ensure that they still pass. In addition, the functionality of the dashboard should be tested to ensure that it still works correctly after the dependency updates.

### Tasks
- [x] Remove all fixed dependencies from `package.json`, unless they are necessary to correct vulnerabilities
- [x] Update the dependencies
- [x] Run the Jest unit tests and ensure that they all pass
- [x] Test the functionality of the dashboard and ensure that it still works correctly

### Hints
Please be careful when updating dependencies, as this can sometimes cause issues with existing code. Make sure to thoroughly test the application after updating the dependencies.
Please use locally all apps you may need to test ( backend, postgres, frontend)

### Information Sharing
Please update this issue with your progress as you work on these tasks. If you encounter any problems or have any questions, feel free to add comments to this issue.
