### ISSUE TITLE
 Update inject-dynamic-env.sh Script to Run with sh Instead of bash

### ISSUE THREAD

**Issue by fabiodmota** [eclipse-tractusx/vas-country-risk#22]
Product Name: [vas-country-risk-frontend](https://github.com/eclipse-tractusx/vas-country-risk-frontend)

### Description
This issue is about updating the `scripts/inject-dynamic-env.sh` script to be run with the default `sh` tool instead of `bash`. This change should be made in a way that does not require installing `bash` in the Dockerfile commands.

### Tasks
- [x] Update the `scripts/inject-dynamic-env.sh` script to be compatible with `sh`
- [x] Test the script to ensure it runs correctly with `sh`
- [x] Update the Dockerfile commands to run the script with `sh` instead of `bash`
- [x] Remove bash installation on Dockerfile

### Hints
Please be careful when updating scripts, as this can sometimes cause issues with existing code. Make sure to thoroughly test the script after updating it.
Test the Dockerfile build locally before using git hub actions

### Information Sharing
Please update this issue with your progress as you work on these tasks. If you encounter any problems or have any questions, feel free to add comments to this issue.
