### ISSUE TITLE
Update Documentation to Reflect New URL

### ISSUE THREAD

**Issue by fabiodmota** [eclipse-tractusx/vas-country-risk#23]
Product Name: [vas-country-risk-frontend](https://github.com/eclipse-tractusx/vas-country-risk) 

### Description
This issue is about validating and updating the documentation in both the frontend and backend repositories. The URL has been switched from `https://github.com/eclipse-tractusx/vas-country-risk-frontend` to `https://github.com/eclipse-tractusx/vas-country-risk`, and the documentation needs to be updated to reflect this change. All `.md` files in both repositories should be validated and updated as necessary.

### Tasks
- [x] Validate the documentation on docs folder in the frontend repository 
- [x] Validate the documentation on docs folder in the backend repository
- [x] Update any references to the old URL in the frontend repository
- [x] Update any references to the old URL in the backend repository
- [x] Validate all `.md` files in the frontend repository
- [x] Validate all `.md` files in the backend repository

### Todos
- [ ] 

### Hints
Please be careful when updating documentation, as incorrect information can lead to confusion. Make sure to thoroughly check all `.md` files and any other documentation.

### Information Sharing
Please update this issue with your progress as you work on these tasks. If you encounter any problems or have any questions, feel free to add comments to this issue.

**Comment by alexsilva-CGI** [comment]
Frontend .MD Files checklist (Except Arc42 and User Guide)
- [X] Changelog 
- [ ] Install -> Remove components Storybook 
- [X] Notice
- [ ] Readme -> Remove components Storybook 
- [ ] All Charts (3 Readme) -> All need version updates
- [X] Security
- [ ] Authors -> Add Cezar

Frontend .MD Files checklist
- [X] Changelog 
- [ ] Install -> Edit running environments links (Dev and Int), JDK 11 -> 17, Remove H2DB info
- [X] Notice
- [ ] Readme -> Remove H2DB info, remove API sample endpoints duplicate section
- [X] Security
- [ ] Authors -> Add Cezar
- [X] Code of conduct
- [X] Contributing
