### ISSUE TITLE
Conduct Tests and Upgrade Application Versions

### ISSUE THREAD

**Issue by fabiodmota** [eclipse-tractusx/vas-country-risk#27]
## Description
Conduct tests to ensure that the new columns, roles, and API mapping are working as expected. In addition, upgrade the versions of the applications being used and maintain a change log documenting the upgrades and associated changes.

## Product Name
[vas-country-risk](https://github.com/eclipse-tractusx/vas-country-risk)

## Tasks
- [x] Test the new columns, roles, and API mapping to ensure they work as expected.
- [x] Upgrade application versions.
- [x] Maintain a change log documenting the application upgrades and associated changes.
