### ISSUE TITLE
24.03 QG Update Documentation on Arc42

### ISSUE THREAD

**Issue by fabiodmota** [eclipse-tractusx/vas-country-risk#75]
## Issue Description
- **Problem:** Update Documentation 

## Product Information
- **Repository Link:** [vas-country-risk](https://github.com/eclipse-tractusx/vas-country-risk)

## Tasks
- [x] **Reformat Arc42:** Ensure that the documentation about the App is updated for the QG 24.03 with EDC implementation
- [x]  **Reformat MD for Converting to PDF:** Ensure that the bottom line is not showing when converting
- [x] **Reformat Images:** Ensure that the PDF contain the Images of the docs folder

**Comment by fabiodmota** [comment]
Quality Gate Done
